version: "3.8"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    
       
